import type { Metadata } from "next";
import "./globals.css";
import PageWrapper from "./components/pageWrapper/PageWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="max-w-3xl bg-black/50 mx-auto flex h-screen flex-col justify-center items-center">
        <div className="bg-white w-full h-[calc(100vh-200px)] rounded-3xl">
          <PageWrapper>{children}</PageWrapper>
        </div>
      </body>
    </html>
  );
}
